name: Assignment CI CD

on:
  push:
    branches: 
        - main
    #[ "main" ]  # This tells GitHub: "Run this every time I push to main"

jobs: 
  # JOB 1: Build & Push (The CI)
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with: 
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}    

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Build Pet Store 1
      - name: Build and Push Store 1
        uses: docker/build-push-action@v5
        with:
          context: ./pet-store
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/pet-store1:latest

      # Build Pet Store 2 using the SAME 'pet-store' folder
      - name: Build and Push Pet Store 2
        uses: docker/build-push-action@v5
        with:
          context: ./pet-store
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/pet-store2:latest
      
      # Build Pet Order using the 'pet-order' folder
      - name: Build and Push Pet Order
        uses: docker/build-push-action@v5
        with:
          context: ./pet-order
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/pet-order:latest